//! Maven project output and the local repository (#67).
//!
//! Maven's `target/` layout is a documented convention
//! (<https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html>)
//! and the local repository lays artifacts out by coordinate, so both
//! can be identified from paths alone.
//!
//! # Downloaded, locally installed, or unknown
//!
//! The one claim this adapter must get right is *origin*, because it
//! decides whether removing an artifact is recoverable at all. The
//! evidence Maven (its Resolver's enhanced local repository manager)
//! leaves beside an artifact, and what each one establishes:
//!
//! * `_remote.repositories` -- a properties file with one key per
//!   artifact file, `<file>><repository-id>=`. A **non-empty** id means
//!   that file was resolved from that remote repository. An **empty** id
//!   (`app-1.0.jar>=`) is the Resolver's `LOCAL_REPO_ID`: the file was
//!   *installed* into the local repository by `mvn install`. So the
//!   file's presence alone proves nothing; its entries do, and they are
//!   read (bounded -- it is a named metadata file of a few hundred
//!   bytes).
//! * `maven-metadata-local.xml` -- written by `mvn install`, beside a
//!   snapshot version or at the artifact level listing installed
//!   versions. Evidence of a local install.
//! * `*.lastUpdated` -- a record that a remote *resolution was
//!   attempted* (usually one that failed or found nothing). It is not
//!   evidence the bytes present were downloaded, so on its own it leaves
//!   the origin unknown and says an attempt was recorded.
//!
//! Local evidence wins over remote evidence for the same version: an
//! artifact downloaded once and later installed over carries both, and
//! "downloaded" would be the guess that costs someone an artifact they
//! cannot fetch again. With no usable evidence the origin is **unknown**,
//! and this adapter says unknown. #67 is explicit: "preserve downloaded
//! versus locally installed or unknown origin without assuming local
//! artifacts can be downloaded again."
//!
//! # What is never done
//!
//! Plugins are never evaluated and POM properties are never resolved. An
//! unresolved `${property}` or a parent-inherited version is an explicit
//! identity gap, never a silently empty result -- the PR #123 review
//! found exactly that shape returning `Ok(vec![])`.

use super::{BuildAdapter, BuildCapabilities, BuildContainer, BuildCtx, NestedUnitBuilder};
use crate::artifact::{ArtifactRole, ArtifactVariant, Membership, NestedArtifact, relative_path};
use crate::entities::Confidence;
use std::path::{Path, PathBuf};

pub struct Adapter;

/// The conventional contents of a Maven `target/` directory.
const TARGET_ENTRIES: &[(&str, ArtifactRole, &str)] = &[
    (
        "classes",
        ArtifactRole::Output,
        "recompiled by the next `mvn compile`",
    ),
    (
        "test-classes",
        ArtifactRole::Output,
        "recompiled by the next `mvn test-compile`",
    ),
    (
        "generated-sources",
        ArtifactRole::Output,
        "regenerated by the next build; source generators run again",
    ),
    (
        "generated-test-sources",
        ArtifactRole::Output,
        "regenerated by the next build",
    ),
    (
        "surefire-reports",
        ArtifactRole::TestOutput,
        "regenerated by the next `mvn test`",
    ),
    (
        "failsafe-reports",
        ArtifactRole::TestOutput,
        "regenerated by the next `mvn verify`",
    ),
    (
        "site",
        ArtifactRole::Output,
        "regenerated by the next `mvn site`",
    ),
    (
        "maven-status",
        ArtifactRole::Metadata,
        "the compiler plugin rewrites it on the next build",
    ),
    (
        "maven-archiver",
        ArtifactRole::Metadata,
        "the archiver plugin rewrites it on the next package",
    ),
    (
        "test-run-info",
        ArtifactRole::Metadata,
        "regenerated by the next test run",
    ),
];

/// What the evidence beside a repository artifact establishes about how
/// it got there.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Origin {
    /// `_remote.repositories` names these remote repositories and no
    /// entry is local.
    Downloaded { repositories: Vec<String> },
    /// An empty repository id in `_remote.repositories`, or a
    /// `maven-metadata-local.xml` naming this version: installed by a
    /// local build.
    LocallyInstalled,
    /// No usable evidence. Swamp does not know, and does not guess.
    Unknown,
}

impl Origin {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Downloaded { .. } => "downloaded",
            Self::LocallyInstalled => "locally-installed",
            Self::Unknown => "unknown-origin",
        }
    }

    fn consequence(&self) -> String {
        match self {
            Self::Downloaded { repositories } => format!(
                "the next build that needs this version downloads it again from {} -- needs \
                 access to that repository",
                repositories.join(", ")
            ),
            Self::LocallyInstalled => "this version was installed from a local build; recreating \
                                       it needs that project's source and an `mvn install`"
                .to_string(),
            Self::Unknown => "swamp found no origin evidence beside this artifact, so it cannot \
                              say whether it can be downloaded again"
                .to_string(),
        }
    }
}

/// An origin plus what established it, and what could not be read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct OriginEvidence {
    pub origin: Origin,
    pub detail: String,
    pub limits: Vec<String>,
}

/// Parses `_remote.repositories` text into `(file, repository id)`
/// pairs. Comment lines (`#`) and anything without a `>` are skipped; an
/// empty id is kept as `""` because that *is* the local-install marker.
pub(crate) fn remote_repository_entries(text: &str) -> Vec<(String, String)> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| {
            let key = l.split_once('=').map(|(k, _)| k).unwrap_or(l);
            let (file, repo) = key.rsplit_once('>')?;
            (!file.is_empty()).then(|| (file.to_string(), repo.to_string()))
        })
        .collect()
}

/// Whether a `maven-metadata-local.xml` lists `version`, read as text:
/// `<version>X</version>` anywhere in it. No XML entity or property is
/// resolved -- an entry that needs resolving does not match.
pub(crate) fn local_metadata_lists(text: &str, version: &str) -> bool {
    text.contains(&format!("<version>{version}</version>"))
}

impl BuildAdapter for Adapter {
    fn trash_roles(&self) -> &'static [ArtifactRole] {
        &[
            ArtifactRole::Output,
            ArtifactRole::TestOutput,
            ArtifactRole::Intermediate,
        ]
    }
    fn id(&self) -> &'static str {
        "maven"
    }

    fn name(&self) -> &'static str {
        "Maven"
    }

    fn capabilities(&self) -> BuildCapabilities {
        BuildCapabilities {
            identifies_shared_stores: true,
            attributes_package_identity: true,
            actions_available: true,
        }
    }

    fn store_kinds(&self) -> &'static [crate::locations::BuildStoreKind] {
        use crate::locations::BuildStoreKind;
        &[BuildStoreKind::MavenRepository]
    }

    fn containers(&self, project_root: &Path, candidates: &[PathBuf]) -> Vec<BuildContainer> {
        if !crate::fs_gate::is_file(project_root.join("pom.xml")) {
            return Vec::new();
        }
        let mut out = Vec::new();
        let mut seen = std::collections::HashSet::new();
        let mut claim = |path: PathBuf| {
            if seen.insert(path.clone()) && crate::fs_gate::is_dir(&path) {
                out.push(BuildContainer::project(
                    "maven",
                    path,
                    project_root.to_path_buf(),
                ));
            }
        };
        claim(project_root.join("target"));
        for c in candidates {
            if c.file_name().and_then(|n| n.to_str()) == Some("target") {
                claim(c.clone());
            }
        }
        out
    }

    fn identify(&self, container: &BuildContainer, ctx: &BuildCtx) -> Vec<NestedArtifact> {
        if container.shared {
            return identify_repository(container, ctx);
        }
        identify_target(container, ctx)
    }
}

fn identify_target(container: &BuildContainer, ctx: &BuildCtx) -> Vec<NestedArtifact> {
    let mut root = NestedUnitBuilder::new(container, ArtifactRole::Output, container.path.clone())
        .is_dir(true)
        .supported_with_reason("a Maven project target directory, in the standard layout")
        .evidence("maven-layout", "standard target layout", Confidence::Medium)
        .consequence("the next `mvn package` regenerates everything it holds");
    match ctx.folded().get(&container.path) {
        Some(d) => root = root.folded(d),
        None => root = root.limit("this directory was not measured by the walk this pass"),
    }
    let mut units = vec![root.build()];

    for child in ctx.folded().children(&container.path) {
        let name = child
            .path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default()
            .to_string();
        let known = TARGET_ENTRIES.iter().find(|(n, _, _)| *n == name);
        let mut b = NestedUnitBuilder::new(
            container,
            known
                .map(|(_, r, _)| r.clone())
                .unwrap_or(ArtifactRole::Residual),
            child.path.clone(),
        )
        .folded(child);
        b = match known {
            Some((_, _, consequence)) => b
                .supported_with_reason(format!(
                    "`target/{name}` is part of Maven's standard directory layout"
                ))
                .evidence(
                    "maven-layout",
                    format!("standard target/{name}"),
                    Confidence::Medium,
                )
                .consequence(*consequence),
            None => b.unsupported_layout(format!(
                "`target/{name}` is not part of the standard layout; a plugin chose it, and swamp \
                 never evaluates plugins"
            )),
        };
        units.push(b.build());
    }

    // Packaged artifacts sit directly in `target/`. Listed shallowly:
    // `target/classes` may hold tens of thousands of class files and
    // none of them is a unit.
    for entry in ctx.list(&container.path) {
        if entry.is_dir {
            continue;
        }
        let packaging = match entry.name.rsplit_once('.') {
            Some((_, ext @ ("jar" | "war" | "ear" | "zip" | "aar"))) => ext,
            _ => continue,
        };
        let path = container.path.join(&entry.name);
        let Some(meta) = ctx.stat(&path) else {
            continue;
        };
        if !meta.is_file() {
            continue;
        }
        let variant = ArtifactVariant {
            configuration: Some(packaging.to_string()),
            // Maven records no build generation: a jar's timestamp says
            // when it was packaged, never that it supersedes another.
            unknowns: vec!["build-generation".into()],
            ..Default::default()
        };
        units.push(
            NestedUnitBuilder::new(container, ArtifactRole::Output, path)
                .from_file_metadata(&meta)
                .variant(variant)
                .supported_with_reason(format!(
                    "a packaged `{packaging}` artifact in the project's target directory"
                ))
                .evidence(
                    "maven-layout",
                    format!("packaged {packaging}"),
                    Confidence::High,
                )
                .consequence("the next `mvn package` repackages it")
                .build(),
        );
    }
    units
}

/// A Maven local repository (`~/.m2/repository` or a configured
/// `localRepository`), handed in as a shared container.
fn identify_repository(container: &BuildContainer, ctx: &BuildCtx) -> Vec<NestedArtifact> {
    let mut root = NestedUnitBuilder::new(
        container,
        ArtifactRole::SharedStoreEntry,
        container.path.clone(),
    )
    .is_dir(true)
    .supported_with_reason("a Maven local repository shared by every Maven build on this machine")
    .evidence("maven-layout", "local repository", Confidence::Medium)
    .consequence(
        "downloaded artifacts are fetched again on the next build; locally installed ones are not \
         -- they need the source project and an `mvn install`",
    )
    .no_action_because("this repository is shared by every Maven project on this machine");
    match ctx.folded().get(&container.path) {
        Some(d) => root = root.folded(d),
        None => root = root.limit("this repository was not measured by the walk this pass"),
    }
    let mut units = vec![root.build()];

    // Version directories are the unit: `<group dirs>/<artifact>/<version>`.
    // A version directory is one whose *parent* chain has at least one
    // more segment and whose own name looks like a version -- which is
    // how a `commons-io/commons-io/2.11.0` is told from the group
    // directories above it without listing anything.
    for dir in ctx.folded().under(&container.path) {
        let rel = relative_path(&container.path, &dir.path);
        if rel.is_empty() {
            continue;
        }
        let name = dir
            .path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default();
        // An unexpanded POM property where a version belongs
        // (`${project.version}`, `${revision}`): a build installed an
        // artifact whose version it never resolved. It is not a
        // version, and it is not silently dropped either -- the PR #123
        // review found exactly that shape returning `Ok(vec![])`.
        if name.contains("${") {
            let mut variant = ArtifactVariant::default();
            variant.unknowns.push("version".into());
            variant.unknowns.push("origin".into());
            if let Some(c) = crate::build_adapters::jvm_common::coordinates_from_relative(
                &relative_path(&container.path, dir.path.parent().unwrap_or(&dir.path)),
                false,
            ) {
                variant.package = Some(format!("{}:{}", c.group, c.artifact));
            }
            units.push(
                NestedUnitBuilder::new(container, ArtifactRole::Residual, dir.path.clone())
                    .folded(dir)
                    .variant(variant)
                    .membership(Membership::Unknown)
                    .unsupported_layout(format!(
                        "`{name}` is an unresolved POM property, not a version: the build that \
                         installed this never resolved it, and swamp never evaluates POMs to \
                         resolve it either"
                    ))
                    .consequence(Origin::Unknown.consequence())
                    .build(),
            );
            continue;
        }
        if !crate::build_adapters::jvm_common::looks_like_version(name) {
            continue;
        }
        let coords = crate::build_adapters::jvm_common::coordinates_from_relative(&rel, false);
        let evidence = origin_of(ctx, &dir.path, name);
        let origin = &evidence.origin;
        let mut variant = ArtifactVariant::default();
        match &coords {
            Some(c) => {
                variant.package = Some(format!("{}:{}", c.group, c.artifact));
                variant.version = c.version.clone();
                variant.configuration = Some(origin.label().to_string());
            }
            None => {
                variant.unknowns.push("package".into());
                variant.unknowns.push("version".into());
            }
        }
        if *origin == Origin::Unknown {
            variant.unknowns.push("origin".into());
        }
        let mut b =
            NestedUnitBuilder::new(container, ArtifactRole::SharedStoreEntry, dir.path.clone())
                .folded(dir)
                .variant(variant)
                .membership(Membership::Unknown)
                .consequence(origin.consequence())
                .no_action_because(
                    "a repository artifact may be a dependency of any project on this machine",
                );
        b = match &coords {
            Some(c) => b
                .supported_with_reason(format!(
                    "the local repository lays artifacts out by coordinate; this is {}",
                    c.display()
                ))
                .evidence(
                    "maven-repository",
                    format!("{} ({})", c.display(), origin.label()),
                    Confidence::High,
                ),
            None => b.unsupported_layout(format!(
                "`{rel}` is not a coordinate layout this adapter can read"
            )),
        };
        b = b.evidence("maven-origin", evidence.detail.clone(), Confidence::High);
        for limit in &evidence.limits {
            b = b.limit(limit.clone());
        }
        if *origin == Origin::Unknown {
            b = b.limit(
                "no usable `_remote.repositories` entry or `maven-metadata-local.xml` for this \
                 version: swamp cannot tell whether it was downloaded or installed locally, and \
                 does not assume it can be downloaded again",
            );
        }
        units.push(b.build());
    }
    units
}

/// The origin evidence Maven left beside one version directory.
///
/// Cost: one capped listing of the version directory; one bounded read
/// of `_remote.repositories` when it is there (a few hundred bytes); and
/// only when it is *not* there, one `stat` plus at most one bounded read
/// of the artifact-level `maven-metadata-local.xml`. `*.lastUpdated`
/// files are never read -- their presence is the whole fact.
pub(crate) fn origin_of(ctx: &BuildCtx, version_dir: &Path, version: &str) -> OriginEvidence {
    let mut remote_file = false;
    let mut local_metadata = false;
    let mut attempted = false;
    for e in ctx.list(version_dir) {
        if e.is_dir {
            continue;
        }
        remote_file |= e.name == "_remote.repositories";
        local_metadata |= e.name == "maven-metadata-local.xml";
        attempted |= e.name.ends_with(".lastUpdated");
    }
    let mut limits = Vec::new();
    if local_metadata {
        return OriginEvidence {
            origin: Origin::LocallyInstalled,
            detail: "maven-metadata-local.xml beside this version (written by `mvn install`)"
                .into(),
            limits,
        };
    }
    if remote_file {
        match ctx.manifest(&version_dir.join("_remote.repositories")) {
            Some(m) if !m.truncated => {
                let entries = remote_repository_entries(&m.text);
                if entries.iter().any(|(_, repo)| repo.is_empty()) {
                    return OriginEvidence {
                        origin: Origin::LocallyInstalled,
                        detail: "_remote.repositories records an empty repository id: installed \
                                 locally"
                            .into(),
                        limits,
                    };
                }
                let mut repositories: Vec<String> =
                    entries.into_iter().map(|(_, repo)| repo).collect();
                repositories.sort();
                repositories.dedup();
                if !repositories.is_empty() {
                    return OriginEvidence {
                        detail: format!(
                            "_remote.repositories records resolution from {}",
                            repositories.join(", ")
                        ),
                        origin: Origin::Downloaded { repositories },
                        limits,
                    };
                }
                limits.push("_remote.repositories has no entries this adapter can read".into());
            }
            Some(_) => limits.push(
                "_remote.repositories is larger than the manifest cap and was not parsed".into(),
            ),
            None => limits.push("_remote.repositories could not be read".into()),
        }
    }
    // Artifact-level install metadata, consulted only when the version
    // directory itself said nothing usable.
    if let Some(artifact_dir) = version_dir.parent() {
        let meta = artifact_dir.join("maven-metadata-local.xml");
        if ctx.stat(&meta).is_some_and(|m| m.is_file()) {
            match ctx.manifest(&meta) {
                Some(m) if !m.truncated && local_metadata_lists(&m.text, version) => {
                    return OriginEvidence {
                        origin: Origin::LocallyInstalled,
                        detail: "the artifact's maven-metadata-local.xml lists this version".into(),
                        limits,
                    };
                }
                Some(m) if m.truncated => limits.push(
                    "the artifact's maven-metadata-local.xml is larger than the manifest cap and \
                     was not parsed"
                        .into(),
                ),
                _ => {}
            }
        }
    }
    if attempted {
        limits.push(
            "a `*.lastUpdated` file records a remote resolution attempt; that is not evidence the \
             bytes here were downloaded"
                .into(),
        );
    }
    OriginEvidence {
        origin: Origin::Unknown,
        detail: "no origin evidence".into(),
        limits,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::artifact::TimeSource;
    use crate::build_adapters::{ContainerCache, FoldedDir, FoldedIndex};
    use crate::fs_events::EventCoverage;
    use std::fs;

    fn index(entries: &[(&PathBuf, u64, u64)]) -> FoldedIndex {
        FoldedIndex::from_dirs(entries.iter().map(|(p, b, m)| FoldedDir {
            path: (*p).clone(),
            allocated_total: *b,
            mtime_max: *m,
            complete: true,
        }))
    }

    fn run(c: &BuildContainer, idx: &FoldedIndex) -> Vec<NestedArtifact> {
        let none = EventCoverage::untrusted();
        let cache = ContainerCache::disabled();
        Adapter.identify(c, &BuildCtx::new(1_000, idx, &none, &cache))
    }

    #[test]
    fn unknown_layout_is_explicit_not_empty() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("target");
        let plugin = target.join("jacoco-ut");
        fs::create_dir_all(&plugin).unwrap();
        let c = BuildContainer::project("maven", target.clone(), tmp.path().to_path_buf());
        let units = run(&c, &index(&[(&target, 100, 500), (&plugin, 60, 500)]));
        let u = units.iter().find(|u| u.path == plugin).expect("a row");
        assert!(!u.coverage.supported);
        assert_eq!(u.role, ArtifactRole::Residual);
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("never evaluates plugins")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn identification_reads_no_more_than_manifest_cap() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("commons-io/commons-io/2.11.0");
        fs::create_dir_all(&v).unwrap();
        // An origin file far larger than the cap: read up to the cap,
        // reported as unparsed, and the origin stays unknown rather than
        // being read from a prefix.
        fs::write(v.join("_remote.repositories"), vec![b'x'; 900_000]).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 1_000, 500),
            (&repo.join("commons-io"), 900, 500),
            (&repo.join("commons-io/commons-io"), 900, 500),
            (&v, 900, 500),
        ]);
        let (units, counted) = crate::work_counters::measured(|| run(&c, &idx));
        assert!(
            counted.header_bytes_read <= super::super::bounded_io::MAX_MANIFEST_BYTES as u64,
            "read {} bytes",
            counted.header_bytes_read
        );
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(u.variant.configuration.as_deref(), Some("unknown-origin"));
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("larger than the manifest cap")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn no_project_or_build_code_is_executed() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        fs::write(root.join("pom.xml"), b"<project/>").unwrap();
        fs::create_dir_all(root.join("target/classes")).unwrap();
        fs::write(root.join("mvnw"), b"#!/bin/sh\nexit 5\n").unwrap();
        let c = BuildContainer::project("maven", root.join("target"), root.to_path_buf());
        let idx = index(&[
            (&root.join("target"), 100, 500),
            (&root.join("target/classes"), 90, 500),
        ]);
        let (_u, counted) = crate::work_counters::measured(|| run(&c, &idx));
        assert_eq!(
            counted.subprocess_spawns, 0,
            "identification spawned a process; Maven and its wrapper are never invoked"
        );
    }

    #[test]
    fn variants_never_collapse_by_basename() {
        // Two versions of one artifact, and two artifacts with the same
        // version. Neither pair may collapse.
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let a1 = repo.join("commons-io/commons-io/2.11.0");
        let a2 = repo.join("commons-io/commons-io/2.15.1");
        let b1 = repo.join("org/slf4j/slf4j-api/2.11.0");
        for p in [&a1, &a2, &b1] {
            fs::create_dir_all(p).unwrap();
        }
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 1_000, 500),
            (&repo.join("commons-io"), 600, 500),
            (&repo.join("commons-io/commons-io"), 600, 500),
            (&a1, 300, 500),
            (&a2, 300, 500),
            (&repo.join("org"), 400, 500),
            (&repo.join("org/slf4j"), 400, 500),
            (&repo.join("org/slf4j/slf4j-api"), 400, 500),
            (&b1, 400, 500),
        ]);
        let units = run(&c, &idx);
        let u1 = units.iter().find(|u| u.path == a1).expect("2.11.0");
        let u2 = units.iter().find(|u| u.path == a2).expect("2.15.1");
        let u3 = units.iter().find(|u| u.path == b1).expect("slf4j 2.11.0");
        assert_ne!(u1.id, u2.id);
        assert_ne!(u1.id, u3.id);
        assert_eq!(u1.variant.version.as_deref(), Some("2.11.0"));
        assert_eq!(u2.variant.version.as_deref(), Some("2.15.1"));
        assert_eq!(u1.variant.package.as_deref(), Some("commons-io:commons-io"));
        assert_eq!(u3.variant.package.as_deref(), Some("org.slf4j:slf4j-api"));
    }

    #[test]
    fn age_is_not_obsolescence() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("commons-io/commons-io/1.0");
        fs::create_dir_all(&v).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let units = run(
            &c,
            &index(&[
                (&repo, 100, 1),
                (&repo.join("commons-io"), 100, 1),
                (&repo.join("commons-io/commons-io"), 100, 1),
                (&v, 100, 1),
            ]),
        );
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(u.time_source, TimeSource::FoldedDirectoryModification);
        assert_eq!(
            u.variant.configuration.as_deref(),
            Some("unknown-origin"),
            "a very old artifact with no origin evidence has an unknown origin, not a presumed one"
        );
        // The verdict-vocabulary scan over every string this unit can
        // put in front of a person lives in
        // `crates/core/tests/build_adapter_contract.rs::no_unit_renders_a_verdict`.
        // It is not repeated here, because spelling the banned words in
        // `crates/core/src` is itself what `scripts/check.sh`'s grep
        // audit rejects -- and a weaker copy of a stronger check is not
        // worth the exemption.
    }

    #[test]
    fn a_locally_installed_artifact_is_never_called_downloadable() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/app/1.0-SNAPSHOT");
        fs::create_dir_all(&v).unwrap();
        fs::write(v.join("maven-metadata-local.xml"), b"<metadata/>").unwrap();
        // Maven writes both markers in some layouts; the local one is
        // the stronger claim and must win.
        fs::write(v.join("_remote.repositories"), b"").unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&repo.join("com/example/app"), 100, 500),
            (&v, 100, 500),
        ]);
        let units = run(&c, &idx);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(
            u.variant.configuration.as_deref(),
            Some("locally-installed")
        );
        let consequence = u.consequence.clone().unwrap_or_default();
        assert!(
            consequence.contains("mvn install"),
            "the consequence names the only way back: {consequence}"
        );
        assert!(
            !consequence.contains("downloads it again"),
            "a locally installed artifact is never promised as re-downloadable: {consequence}"
        );
    }

    #[test]
    fn an_artifact_with_no_evidence_has_an_unknown_origin() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/mystery/9.9");
        fs::create_dir_all(&v).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&repo.join("com/example/mystery"), 100, 500),
            (&v, 100, 500),
        ]);
        let units = run(&c, &idx);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert!(u.variant.unknowns.iter().any(|x| x == "origin"));
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("does not assume it can be downloaded again")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn an_unresolved_pom_property_is_an_explicit_gap_not_an_empty_result() {
        // The PR #123 review found `parse_pom_xml` returning
        // `Ok(vec![])` for a version it could not resolve. The same
        // shape here is a repository directory named
        // `${project.version}`: it is not a version, and the unit says
        // the version is unknown rather than disappearing.
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/app/${project.version}");
        fs::create_dir_all(&v).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&repo.join("com/example/app"), 100, 500),
            (&v, 100, 500),
        ]);
        let units = run(&c, &idx);
        let gap = units
            .iter()
            .find(|u| u.path == v)
            .expect("the gap is a unit, not a missing row");
        assert!(!gap.coverage.supported);
        assert!(gap.variant.unknowns.iter().any(|x| x == "version"));
        assert_eq!(gap.variant.version, None, "a property is never a version");
        assert_eq!(gap.variant.package.as_deref(), Some("com.example:app"));
        assert!(
            gap.coverage
                .limits
                .iter()
                .any(|l| l.contains("unresolved POM property")),
            "{:?}",
            gap.coverage.limits
        );
        assert!(
            units.iter().any(|u| u.path == repo),
            "the repository itself is still identified; the gap is one entry, not the store"
        );
    }

    fn one_version(files: &[(&str, &[u8])]) -> (tempfile::TempDir, PathBuf, Vec<NestedArtifact>) {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/lib/2.0");
        fs::create_dir_all(&v).unwrap();
        for (name, body) in files {
            fs::write(v.join(name), body).unwrap();
        }
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&repo.join("com/example/lib"), 100, 500),
            (&v, 100, 500),
        ]);
        let units = run(&c, &idx);
        (tmp, v, units)
    }

    #[test]
    fn a_remote_repository_entry_means_downloaded_from_that_repository() {
        let (_t, v, units) = one_version(&[(
            "_remote.repositories",
            b"#NOTE: This is a Maven Resolver internal implementation file\n\
              lib-2.0.jar>central=\nlib-2.0.pom>central=\n",
        )]);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(u.variant.configuration.as_deref(), Some("downloaded"));
        let consequence = u.consequence.clone().unwrap_or_default();
        assert!(consequence.contains("central"), "{consequence}");
    }

    #[test]
    fn an_empty_repository_id_is_a_local_install_not_a_download() {
        // The tempting reading: `_remote.repositories` exists, so the
        // artifact was downloaded. The Resolver writes the same file for
        // `mvn install`, with an empty repository id -- and promising a
        // re-download of that is the guess that costs an artifact.
        let (_t, v, units) =
            one_version(&[("_remote.repositories", b"lib-2.0.jar>=\nlib-2.0.pom>=\n")]);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(
            u.variant.configuration.as_deref(),
            Some("locally-installed")
        );
        assert!(
            !u.consequence
                .clone()
                .unwrap_or_default()
                .contains("downloads it again")
        );
    }

    #[test]
    fn a_last_updated_marker_alone_leaves_the_origin_unknown() {
        let (_t, v, units) = one_version(&[(
            "lib-2.0.jar.lastUpdated",
            b"https\\://repo.example/.error=Not found\n",
        )]);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(u.variant.configuration.as_deref(), Some("unknown-origin"));
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("resolution attempt")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn a_malformed_origin_file_is_an_explicit_unknown() {
        let (_t, v, units) = one_version(&[("_remote.repositories", b"garbage without markers")]);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(u.variant.configuration.as_deref(), Some("unknown-origin"));
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("no entries this adapter can read")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn artifact_level_install_metadata_marks_only_the_versions_it_lists() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let art = repo.join("com/example/lib");
        let listed = art.join("1.0");
        let unlisted = art.join("1.1");
        fs::create_dir_all(&listed).unwrap();
        fs::create_dir_all(&unlisted).unwrap();
        fs::write(
            art.join("maven-metadata-local.xml"),
            b"<metadata><versioning><versions><version>1.0</version></versions></versioning>\
              </metadata>",
        )
        .unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&art, 100, 500),
            (&listed, 50, 500),
            (&unlisted, 50, 500),
        ]);
        let units = run(&c, &idx);
        let a = units.iter().find(|u| u.path == listed).unwrap();
        let b = units.iter().find(|u| u.path == unlisted).unwrap();
        assert_eq!(
            a.variant.configuration.as_deref(),
            Some("locally-installed")
        );
        assert_eq!(
            b.variant.configuration.as_deref(),
            Some("unknown-origin"),
            "install metadata for one version says nothing about its sibling"
        );
    }

    #[test]
    fn a_local_only_artifact_in_a_project_output_and_repository_stays_distinct() {
        // A project that `mvn install`s itself: its own `target/*.jar`
        // and the installed copy in the repository are two units with
        // two consequences, not one artifact seen twice.
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().join("app");
        let target = root.join("target");
        fs::create_dir_all(&target).unwrap();
        fs::write(root.join("pom.xml"), b"<project/>").unwrap();
        fs::write(target.join("app-1.0.jar"), vec![1u8; 4096]).unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/app/1.0");
        fs::create_dir_all(&v).unwrap();
        fs::write(v.join("_remote.repositories"), b"app-1.0.jar>=\n").unwrap();
        let t_units = run(
            &BuildContainer::project("maven", target.clone(), root.clone()),
            &index(&[(&target, 8, 500)]),
        );
        let r_units = run(
            &BuildContainer::shared_store("maven", repo.clone()),
            &index(&[
                (&repo, 8, 500),
                (&repo.join("com"), 8, 500),
                (&repo.join("com/example"), 8, 500),
                (&repo.join("com/example/app"), 8, 500),
                (&v, 8, 500),
            ]),
        );
        let jar = t_units
            .iter()
            .find(|u| u.path == target.join("app-1.0.jar"))
            .unwrap();
        let installed = r_units.iter().find(|u| u.path == v).unwrap();
        assert_ne!(jar.id, installed.id);
        assert_ne!(jar.container_id, installed.container_id);
        assert!(
            installed
                .consequence
                .as_deref()
                .unwrap()
                .contains("mvn install")
        );
        assert!(jar.consequence.as_deref().unwrap().contains("mvn package"));
    }

    #[test]
    fn an_incompletely_measured_target_says_so_and_stays_identified() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("target");
        fs::create_dir_all(&target).unwrap();
        let partial = FoldedIndex::from_dirs([FoldedDir {
            path: target.clone(),
            allocated_total: 2_000,
            mtime_max: 500,
            complete: false,
        }]);
        let units = run(
            &BuildContainer::project("maven", target.clone(), tmp.path().to_path_buf()),
            &partial,
        );
        let u = &units[0];
        assert!(!u.coverage.complete);
        assert!(u.coverage.supported, "incomplete is not unsupported");
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("could not read all of this directory")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn a_missing_pom_claims_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        fs::create_dir_all(tmp.path().join("target")).unwrap();
        assert!(
            Adapter.containers(tmp.path(), &[]).is_empty(),
            "a `target/` with no pom.xml beside it is not Maven's"
        );
    }
}
