[package]
name = "swamp-tui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
swamp-core = { path = "../core" }
ratatui = "0.29"
crossterm = "0.28"
unicode-width = "0.2"
unicode-segmentation = "1.13"

[dev-dependencies]
swamp-core = { path = "../core", features = ["testing"] }
tempfile.workspace = true

[lints]
workspace = true
